type: chart
configs:
  - chart: logging-client
    release: logging-client
    retries: 2
    timeout: 900
    test: 
      values:
    stage: 
      values:
prod: 
  doDeploy: none
  #doDeploy: versionfile
