type: chart
configs:
  - chart: logging-client
    release: logging-client
    test: 
      values:
    stage: 
      values:
helmRepos:
   - name: cnct-migrations
     url: http://charts.migrations.cnct.io
prod: 
  doDeploy: none
  #doDeploy: versionfile
